### ISSUE TITLE
How is this better than Google' Data Saver extension?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [niutech/datacompressionproxy#54]
```
Is this superfluous to Googles extension or does this do something differently, 
please explain.


Thank you


```

Original issue reported on code.google.com by `dovidba...@gmail.com` on 11 Aug 2015 at 7:24

**Comment by niutech** [comment]
DCP was made before [Dava Saver](https://chrome.google.com/webstore/detail/data-saver-beta/pfmgfdlgomnbgkofeojodiodmgpgmkac) was available. Nowadays you should use the latter extension.
